#logical operator
a = True
b = False
print(a and b)
print(a or b)
print(not a)
print(not b)
print(a and not b)
print(a or not b)
print(not a and b)
print(not a or b)
print(not a and not b)
print(not a or not b)
print(not (a and b))
print(not (a or b))
print(not (not a and b))
print(not (not a or b))
print(not (a and not b))
print(not (a or not b))
print(not (not a and not b))
print(not (not a or not b))
print(not (not (a and b)))
print(not (not (a or b)))
print(not (not (not a and b)))
print(not (not (not a or b)))
print(not (not (a and not b)))
print(not (not (a or not b)))
print(not (not (not a and not b)))
print(not (not (not a or not b)))
print(a and b or not a)
print(a or b and not a)